import csv
import random

# Categorías y descripciones por categoría
categorias = {
    "Alimentación": [
        "REFRESCO NARANJA", "PALOMITAS MICROON", "(P)LECHE SEMIDESN", "SALERO COVIRAN 20",
        "(P)AZUCAR COVIRAN", "YATEKOMO POLLO GA", "TRONQUITOS DE MAI", "SURIMI AL AJILLO",
        "MINI BISCOTTE COV", "EMPANADILLAS ATUN", "YATEKOMO YAKISOBA", "AJO GRANULADO LA",
        "PATE DE CERDO COV", "TACOS CALAMAR AL", "PALETA DE CERDO I",
        "GELATINA DE FRESA", "BATIDO DE CHOCOLATE", "GALLETAS MARÍA", "FIDEOS CHINOS",
        "TORTILLAS DE MAÍZ", "SOPA INSTANTÁNEA", "ACEITE OLIVA VIRGEN", "CEREALES DESAYUNO",
        "ARROZ BASMATI", "PAPAS FRITAS", "HAMBURGUESAS VEGETALES", "MERMELADA DE DURAZNO",
        "GALLETAS DE CHOCOLATE", "PESCADO ENLATADO", "JUGO DE MANZANA", "VINAGRE BALSÁMICO"
    ],
    "Ropa": [
        "BOLSA CAMISETA 48", "ZAPATILLAS DEPORTIVAS", "CAMISETA ALGODÓN", "PANTALONES VAQUEROS",
        "CHAQUETA INVIERNO", "BOLSA CAMISETA", "ZAPATOS CASUAL", "SUDADERA DE ALGODÓN",
        "PANTALONES CORTOS", "FALDA VERANO", "CHALECO TÉCNICO", "GORRA DE SOL",
        "GUANTES DE INVIERNO", "CINTURÓN DE PIEL", "BUFANDA DE LANA",
        "CAMISA DE CUADROS", "MEDIAS LARGAS", "PANTALONES DE CHÁNDAL",
        "VESTIDO DE NOCHE", "PANTALONES FORMAL", "CAMISETA DE DEPORTE",
        "BOLSO DE MANO", "BOLSO DE BANDOLERA", "CHAQUETA DE PIEL", "SANDALIAS DE VERANO",
        "TACONES ALTO", "BOTA DE NIEVE", "SANDALIAS DE PIEL", "ZAPATILLAS DE CASA",
        "PANTALONES DE YOGA"
    ],
    "Electrónica": [
        "AURICULARES BLUETOOTH", "PORTÁTIL HP GAMER", "CARGADOR USB TIPO C", "TELEVISOR SMART TV",
        "ASPIRADORA ROBOT", "CONSOLA DE VIDEOJUEGOS", "CARGADOR DE COCHE", "BATERÍA RECARGABLE",
        "SMARTWATCH", "TABLET SAMSUNG", "CÁMARA DIGITAL", "TELEFONO INTELIGENTE",
        "ALTAVOZ INTELIGENTE", "MONITOR 4K", "PROYECTOR PORTÁTIL", "TECLADO MECÁNICO",
        "MOUSE GAMER", "PANTALLA PORTÁTIL", "DVR PARA CÁMARAS", "MICRÓFONO USB",
        "HARD DRIVE EXTERNO", "CÁMARAS DE SEGURIDAD", "ROUTER WIFI", "LAPTOP ACER",
        "HEADSET GAMER", "CÁMARA DE ACCIÓN", "AURICULARES INALÁMBRICOS",
        "CARGADOR INALÁMBRICO", "DRON CON CÁMARA", "PROYECTOR HD",
        "VENTILADOR PORTÁTIL"
    ],
    "Limpieza": [
        "DETERGENTE LIQ.AD", "SUAVIZANTE CONCEN", "BOLSA BASURA AUT", "PAPEL HUMEDO WC C",
        "JABÓN LÍQUIDO", "TOALLITAS DESINFECTANTES", "DESINFECTANTE MANOS", "JABÓN DE MANOS",
        "LIMPIADOR MULTISUPERFICIE", "ESCOVILLAS DE BAÑO", "CUBO DE FREGAR",
        "ESFREGONA CON MANGO", "DESINFECTANTE SPRAY", "PAÑOS DE MICROFIBRA",
        "BOLSAS DE BASURA RECICLABLES", "LIMPIAPARABRISAS", "PULVERIZADOR LIMPIADOR",
        "PAÑOS LIMPIA VIDRIOS", "BOLSAS DE PLÁSTICO", "BICICLETA DE LIMPIEZA",
        "LIMPIADOR DE FREGADERO", "GUANTES DE LIMPIEZA", "CEPILLO PARA ROPA",
        "LIMPIADOR DE OLORES", "PAÑOS DE TELA", "DESENGRASANTE",
        "TRAPOS DE LIMPIEZA", "LIMPIADOR DE PAVIMENTO", "LIMPIADOR DE MUEBLES",
        "LIMPIADOR DE BAÑO", "LIMPIADOR DE MUEBLES", "JABÓN PARA ROPA"
    ],
    "Salud": [
        "MASCARILLA FFP2", "IBUPROFENO 600MG", "PARACETAMOL 500MG", "PASTILLAS PARA GARGANTA",
        "CREMA SOLAR SPF50", "PASTA DE DIENTES", "VITAMINA C", "SUPLEMENTO DE HIERRO",
        "ANTIBIÓTICO EN CREMA", "ANALGÉSICO", "VITAMINA D", "PILAS PARA MEDICINA",
        "TERMÓMETRO DIGITAL", "TENSIÓMETRO", "DESINFECTANTE DE SUPERFICIE",
        "COMPRESAS FRÍAS", "BANDA ELÁSTICA", "CINTURILLA", "LENTES DE CONTACTO",
        "CREMA HIDRATANTE", "GEL ANTIBACTERIAL", "PAQUETE DE VENDAS",
        "ANTISÉPTICO", "PASTILLAS ANTIHISTAMÍNICAS", "JERINGAS DESCARTABLES",
        "TERMÓMETRO ANAL", "PASTILLAS PARA LA TOS", "GEL PARA DOLOR MUSCULAR",
        "CREMA PARA EL ACNÉ", "BOLSA DE HIELO"
    ],
    "Ocio": [
        "ENTRADA DE CINE", "VIDEOJUEGO CONSOLA", "PELICULA EN STREAMING", "SUBSCRIPCIÓN NETFLIX",
        "BOLETO CONCIERTO", "JUEGO DE MESA", "LIBRO DE FANTASÍA", "REVISTA DE MODA",
        "PÓSTER DE PELÍCULA", "TICKET PARA EL ZOO", "TICKET DE MUSEO",
        "VIAJE EN TREN", "EXCURSIÓN GUIADA", "CLASE DE COCINA", "CLASE DE YOGA",
        "PASE ANUAL DE PARQUE TEMÁTICO", "PAQUETE DE VIAJE", "TICKET PARA UN EVENTO",
        "JUEGO DE CARTAS", "SET DE DIBUJO", "PAQUETE DE PINTURAS", "MATERIALES DE ESCUELA",
        "PASE DE CINE", "LIBRO DE COCINA", "PANTALLA DE CINE", "EVENTO DE MUSICA EN VIVO",
        "LIBRO DE AUTOAYUDA", "CLASE DE PINTURA", "FESTIVAL DE CINE", "ESPECTÁCULO DE MAGIA"
    ],
    "Transporte": [
        "BILLETE DE METRO", "TARJETA DE TRANSPORTE", "COMBUSTIBLE GASOLINA", "BOLETO DE AVIÓN",
        "BICICLETA", "AUTOBÚS", "TICKET DE PARKING", "CARNET DE CONDUCIR",
        "TAXI", "VIAJE EN AUTOCAR", "ALQUILER DE COCHE", "TICKET DE TRANSPORTE PÚBLICO",
        "MANTENIMIENTO DE COCHE", "SEGURO DE COCHE", "CARGADOR DE COCHE ELÉCTRICO",
        "RECARGA DE TARJETA DE TRANSPORTE", "TICKET DE TREN", "VIAJE EN TAXI",
        "SERVICIO DE AUTOBÚS", "BICICLETA ELÉCTRICA", "TARJETA DE BUS",
        "TICKET DE VUELO", "PARQUIMETRO", "BOLSA DE TRANSPORTE", "MULTA DE TRÁFICO",
        "ALQUILER DE BICICLETA", "PASE DE TRANSPORTE", "BICICLETA PLEGABLE",
        "PASAJERO DE TREN", "TARJETA DE BUS GRATIS"
    ],
}

# Generar 1000 filas aleatorias
filas = []
for _ in range(1000):
    categoria = random.choice(list(categorias.keys()))
    descripcion = random.choice(categorias[categoria])
    filas.append([descripcion, categoria])

# Guardar en archivo CSV
with open('dataset_compras.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["descripcion", "categoria"])  # Escribir la cabecera
    writer.writerows(filas)

print("Dataset generado con éxito.")
